### ISSUE TITLE
Model Type Specification

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaLSM.jl#14]
What is the best way to subtype a land model component such that its configuration is apparent e.g. a soil model could run in a simple `RichardsModel` mode or in a more complex model.

See [ClimaAtmos](https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/Models/Models.jl) `ModelStyles`.

**Comment by jakebolewski** [comment]
Instead of subtyping you might want to look into a simple type trait interface, this makes it more compositional: https://invenia.github.io/blog/2019/11/06/julialang-features-part-2/

**Comment by jb-mackay** [comment]
Thanks for sharing! I'll keep this in mind - I don't see quite yet where we would employ this but this is the first I'm learning about traits.

**Comment by jb-mackay** [comment]
For now, subtyping is working.
