### ISSUE TITLE
Check in Manifest for experiments, and avoid using LOAD_PATH in experiments

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaLSM.jl#155]
## Describe the bug

To ensure that the experiments can be reproduced if packages are updated, it is helpful to check in `experiments/Manifest.toml`. That way there is a known working set of packages that can be used to run the experiments.

If you do this, then you should remove the `LOAD_PATH` changes in the experiments files (e.g. https://github.com/CliMA/ClimaLSM.jl/blob/51d561608c85edab1430047b218ca5185d33c8b1/experiments/LSM/ozark_test.jl#L14-L16), and instead `]dev ..` to make sure that the Manifest is using the correct vertsion of ClimaLSM.jl

**Comment by simonbyrne** [comment]
This also appeared to be the cause of the issues @gagnelandmanna was having.

**Comment by kmdeck** [comment]
@simonbyrne  Is using `]dev .. ` and making the ClimaLSM package part of the experiments/test/docs project environments the recommended approach? vs the LOAD_PATH one, where it is not part of the experiments/test/docs environments?
