### ISSUE TITLE
Streamline `NotIncluded` Model Type

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaLSM.jl#16]
It would be nice if subcomponents not included in a LSM configuration (e.g. no snow model in the biosphere + biophysics configuration) did not get added to the state, if even by name only.

**Comment by kmdeck** [comment]
this may be useful to us:
https://github.com/CliMA/ClimaAtmos.jl/blob/ec56b8453712bff8e8662030993af3ec89b8b582/src/Models/Nonhydrostatic3DModels/nonhydrostatic_3d_model.jl#L57

(we'd still have NotIncluded, but then wouldnt show up in Y?)
