### ISSUE TITLE
Plant hydraulics model cleanup

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#174]
We are moving towards running the plant hydraulics model only via the canopy model interface. In this case, 
- we dont need to supply the domain as part of the plant hydraulics model - we can supply it just in the canopy model.
- ideally, the LAI is just supplied once
- we really need to clean up `transpiration` because it is quite confusing right now.

**Comment by gagnelandmanna** [comment]
awesome, thank you for following up on my comments

**Comment by kmdeck** [comment]
the LAI, RAI, and SAI will eventually be spatially varying and stored in the aux state, not in a parameter struct. so for now, we won't address that with other changes.
