### ISSUE TITLE
Upgrade to Julia 1.9

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#196]

**Comment by kmdeck** [comment]
@AlexisRenchon do you think you might have time to do this during this sprint?

**Comment by AlexisRenchon** [comment]
I have been running ClimaLSM on 1.9 for a while, never had any problems, I imagine we just have to up the compat in our Project.toml files?

**Comment by kmdeck** [comment]
sweet! that would be easy :)

**Comment by AlexisRenchon** [comment]
We could test this afternoon, as we merge Ozark experiment with complete soil - if it's that simple, maybe we shouldn't open a PR just for julia 1.8 -> julia 1.9

**Comment by kmdeck** [comment]
It was easy enough to do and I had some free time so I made this PR
https://github.com/CliMA/ClimaLSM.jl/pull/204
