### ISSUE TITLE
Tempest Remap bug on cluster

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#217]
## Describe the bug
As of Wed May 24, buildkite runs passed on the cluster
E.g.: https://buildkite.com/clima/climalsm-ci/builds/1118
Possibly relevant: ClimaComms v0.4.2, ClimaCore 10.35, ClimaCoreTempestRemap v0.3.8
Today, it does not run (this is a different PR, but same versions of the above three)
https://buildkite.com/clima/climalsm-ci/builds/1123

Stacktrace
https://buildkite.com/clima/climalsm-ci/builds/1123#0188541e-f5e7-45e7-bf6a-d87ce6269b1b/144-157

The same test passes locally and on github actions (it is included in our unit test suite). But it fails on the cluster in buildkite.

This may be due to an incompatibility between `TempestRemap_jll` and `HDF5_jll.jl` introduced in a recent `HDF5_jll.jl` update. This issue will hopefully be fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/6798.

**Comment by mkitti** [comment]
To be clear, I believe the issue was a HDF5_jll.jl update, not the HDF5.jl update.

**Comment by giordano** [comment]
Should have been fixed by https://github.com/JuliaRegistries/General/pull/84258 already.

**Comment by kmdeck** [comment]
#84258 fixed it - thank you!
