### ISSUE TITLE
Broken incremental precompilation

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaLSM.jl#233]
## Describe the bug
I just saw this warning when loading ClimaLSM:

```julia
[ Info: Precompiling ClimaLSM [7884a58f-fab6-4fd0-82bb-ecfedb2d8430]
WARNING: Method definition imp_tendency!(Any, Any, Any, Any) in module ClimaLSM at /Users/charliekawczynski/.julia/packages/ClimaLSM/T5qIZ/src/ClimaLSM.jl:125 overwritten at /Users/charliekawczynski/.julia/packages/ClimaLSM/T5qIZ/src/ClimaLSM.jl:132.
  ** incremental compilation may be fatally broken for this module **
```
It looks like the issue is related to `imp_tendency!`. There appear to be a lot of functions returning functions in ClimaLSM, we may want to move away from this pattern since it can make stack traces a bit more opaque.

**Comment by kmdeck** [comment]
@charleskawczynski  

just a note, I think we fixed this particular error. you may need to dev .. to make sure you are using the current version and not the last registered version (for anything in docs or experiments)

**Comment by charleskawczynski** [comment]
Ah, right, I think I forgot to dev in the test directory, sorry for the noise!
