### ISSUE TITLE
Type pirating `zero` on `NTuple`s

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaLSM.jl#235]
## Describe the bug
ClimaLSM seems to be type-pirating `zero` on `NTuple`s:

```julia
function Base.zero(x::Type{NTuple{N, FT}}) where {N, FT}
    ntuple(i -> FT(0), N)
end
```

This definition needs to be removed. Please see https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy-1

**Comment by kmdeck** [comment]
what would you recomend we replace it with?

In our model setup, the user specifies the symbols & types of the prognostic and aux variables, and then we create the field vector for Y and p using zero() on the type (for every point in the domain):
https://github.com/CliMA/ClimaLSM.jl/blob/52e122d23285b5fad81e544ce51604eb37a9ca68/src/SharedUtilities/models.jl#L269

so every variable type `T` needs to have `zero(T)` defined for it.

Maybe a quick workaround, without refactoring the entire initialize function, is to not use a new method but to use an if statement in initialize? this isnt a great solution though.

**Comment by kmdeck** [comment]
oh, that's great, an easy fix on this then :) thanks!
