### ISSUE TITLE
Cannot run simulations with Float32

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#327]
## Describe the bug
In ClimaTimesteppers, the float type of the time `t` is Float64. In several places, we require the type of the time variable and the underlying type of the state vectors to be the same. We need to relax this. We also need to change functions where we prescribed driving data as a function of time, so that whatever is returned is converted to the right type.

Close https://github.com/CliMA/ClimaLSM.jl/issues/229 at the same time

See https://github.com/CliMA/ClimaCoupler.jl/issues/396 for discussion with more details

**Comment by kmdeck** [comment]
> Can you provide a MWE? I thought that ClimaTimesteppers inherits the float type.

hey Charlie! That was our assumption too, which is why we built this in. but see this discussion:https://github.com/CliMA/ClimaCoupler.jl/issues/396

**Comment by charleskawczynski** [comment]
🎉

**Comment by kmdeck** [comment]
🎉 !!
