### ISSUE TITLE
empty model components create FieldVector of Vector of Fields

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLSM.jl#356]
## Describe the bug
In some of our model setups, we end up with a state that is a `FieldVector` containing other `FieldVectors` (this is okay), and also containing `Vectors` of `Fields` :exploding_head: (this is not okay).

Specifically, simulations using `CanopyModel` (`canopy_tutorial.jl, soil_canopy_tutorial.jl, ozark.jl`) fail when trying to update ClimaTimeSteppers from v0.7.7 to v0.7.8 (or any more recent version). We believe this is because `initialize_vars` sets empty model components to `FT[]` [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/src/shared_utilities/models.jl#L302). This is preventing us from using the latest ClimaTimeSteppers.

The change in CTS that causes this setup to break is that [v0.7.7](https://github.com/CliMA/ClimaTimeSteppers.jl/blob/v0.7.7/src/solvers/imex_ark.jl#L33) calls `similar(state)`, and [v0.7.8](https://github.com/CliMA/ClimaTimeSteppers.jl/blob/v0.7.8/src/solvers/imex_ark.jl#L35) calls `zero(state)`, which fails for this `FieldVector{Vector{Field}}` structure.

## Possible fix
Instead of returning `FT[]` from initialize_vars, return `nothing`. Then, where `initialize_vars` is called from (`initialize_prognostic`, `initialize_aux`), we can filter out these empty components when constructing the actual state or cache object.

## To Reproduce
```julia
using ClimaCore: Geometry, Meshes, Domains, Topologies, Spaces, Fields
using ClimaComms
using ClimaLSM.Domains: Point


FT = Float64
domain = Point(; z_sfc = FT(0.0))
space = domain.space.surface

field1 = Fields.ones(space)
field2 = Fields.zeros(space)
fieldvec = [field1, field2]
fv1 = Fields.FieldVector(; field1, field2)
fv2 = Fields.FieldVector(; fv1, fieldvec)

zero(fv1)
zero(fv2)
```

## To Do
- implement fix
- add test for undesired behavior

cc @kmdeck

**Comment by kmdeck** [comment]
@juliasloan25 perhaps we can revisit this sooner rather than later. if we try and `resolve` our Manifest in the exp folder, we cannot because of un-satisfiable requirements. May be related: Natan Holtzman, who is at Stanford and trying to use the model, is having a local error with a clone of main that prevents precompilation. if he upgrades ClimaTimeSteppers, he doesnt get that error, but then gets the error referenced in this issue.


```
The specific error I'm getting with precompiling the packages is
ERROR: LoadError: InitError: could not load library "C:\Users\natan\.julia\artifacts\22c03bf198204cc536cb4477e16d5ffd4455391f\bin\cublas64_11.dll"
The specified module could not be found.
[10:05](https://climate-machine.slack.com/archives/D01DC4A1TR7/p1698339907223169)
It's looking for a file on my computer that doesn't exist
[10:05](https://climate-machine.slack.com/archives/D01DC4A1TR7/p1698339917839359)
So maybe it's a specific problem with my computer or Windows 11
[10:07](https://climate-machine.slack.com/archives/D01DC4A1TR7/p1698340048226619)
But it's weird that CUDA v5.0.0 works fine on my computer, it's just the older CUDA version that is required by the experiments environment which does not work
```
