### ISSUE TITLE
Revisit the state array structure

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#4]
Y.component.variable vs Y.variable, same for aux variables, in LSM runs vs standalone runs.

**Comment by jb-mackay** [comment]
Copying over some discussion  of the aux variables from PR #2.

Ben: 
> My instinct is to not have model_name as part of `p`, since a particular `p` already belongs to a particular model, right? The only case were I would want `p.model_name` is a multi-component LSM run.

Kat:
> Agreed - we dont really want the hierarchy in a single component run. But I thought we had worked out that we need to pass the entire `p` in the LSM run to each component RHS (due to shared variables). and so for consistency in the RHS function, we also need to pass the entire p in single component mode. that is, the arguments to `rhs_component!` can be `dY,Y,p,t` and we always store variables in `Y` and `p` as `Y.component`, `p.component`, or we can pass
`dY.component, Y.component,p,t` and just unpack `p`...

> Maybe we can give the `p` we pass additional structure? like pass `p_component` (with no hierarchy) and `p_interactions` as separate pieces, and in single component mode `p_interactions` could be nothing.

**Comment by jb-mackay** [comment]
#45 specifies the direction we are taking here.
