### ISSUE TITLE
Change `interaction_domains` flags

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaLSM.jl#58]
Maybe instead of associating them with a component, we can associate them with a part of the LSMDomain? This is split into subsurface and surface domains (domain.subsurface, domain.surface). It would be more in line with them being shared to pass in :surface or :subsurface rather than e.g. :soil?

_Originally posted by @kmdeck in https://github.com/CliMA/ClimaLSM.jl/pull/51#discussion_r868010858_

**Comment by jb-mackay** [comment]
If we want this, we need to formalize how we associate components with different parts of the domain. 

Currently, `initialize_interactions` (and other init methods) are passed the model and the coords. The variables are then initialized using a space from `coords`. The `coords` struct is a FieldVector, accessed like `coords.soil`. We somehow need to get from the `:surface` or `:subsurface` flags to the relevant model component names so that we can access `coords` correctly.

---

A thought for further down the line - when we adopt ClimaSimulations, the Simulation struct could be a good place to store the model spaces. We could then define `coordinates(simulation)` to return the already constructed spaces, which would make things easier in the initialization as we could call `coordinates` more freely.

@kmdeck

**Comment by jb-mackay** [comment]
A potential plan:

Reorganize `coordinates(::AbstractLandModel)` by `surface` or `subsurface` (any other types? we will see - canopy airspace). So instead of `coordinates.soil` returning the soil coordinates, there would be `coordinates.surface` and `coordinates.subsurface`.  Then, define a method like `domain(model)` (similar to `name(model)`) which returns the correct flag for each component. For example, `domain(::AbstractSoilModel) = :subsurface`.

Then we just would need to call `getproperty(coords, domain(model))` during the initialization. It is also consistent with the current LSMDomain structs (e.g. `LSMSingleColumnDomain`) which have surface and subsurface fields.

**Comment by kmdeck** [comment]
This is what we implemented :) Closing the issue
