### ISSUE TITLE
Suggestions of improvements to bring to the roots file

### ISSUE THREAD

**Issue by gagnelandmanna** [CliMA/ClimaLSM.jl#70]
Hi Katherine and Emma! I included a list of items I think we should modify in the roots file, and a link to the most updated file (Mon. June 27) with the roots model. The file also compares the new plant hydraulic model against a finely resolved Richard's equation (truth) for a simulation in which both under and over saturation regime equations are tested, for different simulation times, and computes the absolute error between the model and the truth.

https://github.com/CliMA/ClimaLSM.jl/blob/ALG_roots_Richards/src/Vegetation/root_test_against_Richards.jl

**Is your feature request related to a problem? Please describe.**

1) To match soil model, and rest of Clima, replace all units with SI units. Change flow equations to flux, and use same units as soil model to facilitate passing variables between both.

2) The model won't currently go above saturation, I think we need to add in this capability.

3) The current flux equation used is a bit more complex (needs two functions) and does not work when the pressure values in adjacent compartments are equal (division by P2-P1) and may lead to numerical errors when the pressures are very similar, so it would be a good idea to include the alternative flux equation described in the docs and in the link included above. 

4) There are several different volume to pressure equations we can use, which are more or less complex. I think adding the linear and Christoffersen volume to pressure functions in, and renaming them to suggested names (below) would be useful. 

5) Like soil model, it would be great to keep parameters in a separate file.

6) It would also be useful to be able to switch between a high resolution single-tree simulation and a grid-scale set up, to suit different needs.

**Describe the solution you'd like**

1) Unit changes : flow (in mol s-1) to flux (m s-1). See flux equations in the root_test_against_Richards file in the link above, I made the conversion here. See also bulk roots section. Note : the flux_Yujie equation needs to be revised in the file (working on this), I used the alternative flux equation (entitled flux) for the tests performed in this file.

2) Change state variable to augmented liquid fraction, add in branch in the absolute pressure function. See file.

3) Add in alternative flux equation (see file).

4) Replace the volume to pressure function name with more specific name such as van_genuchten_volume_to_pressure for the one that is already included, and add a function for a linear_pressure_to_volume as this is commonly used (eg. Nathan used this, I did while developing as well), and another for the christoffersen_volume_to_pressure. Please see file for examples of these functions.

5) Move parameters out of file as is done in soil model.

6) Add in equations for grid scale set-up (see Ozark file). Add in a type or functionality to switch between a one-tree set up and a grid scale set-up

**Describe alternatives you've considered**

**Additional context**
Included a link. See above.

**Comment by gagnelandmanna** [comment]
I will be reviewing the file attached in next few days as there is a bug which is causing me to not being able to represent the overstaturated regime accurately. I will keep you posted on any changes I bring which would affect the suggestions or solutions proposed in the file attached

**Comment by kmdeck** [comment]
@gagnelandmanna it's great that you made this issue a while back! Please keep using it and close when it's ready (it looks like it's ready to close after the area index work?).

One thought - If you set RAI, LAI, SAI all to one, does it reduce to what you have currently (single tree mode)?

**Comment by gagnelandmanna** [comment]
Ok, will do both! 

I think the only thing that hasn't been done from the list apart from the AIs is storing parameters in a separate file from the main PlantHydraulics src file - I just checked the soil model to double check how this was done there. Maybe this isn't necessary for now though for the plants as the model only has one mode and is fairly simple, it could be nice for consistency though?

_One thought - If you set RAI, LAI, SAI all to one, does it reduce to what you have currently (single tree mode)?_ Yes, but for simplicity in the iteration we currently have in main, I assumed all conducting area terms were equal (the conducting area of roots = that of stem = that of leaves). In a better single tree mode, there would a term for each conducting area (in m2), but this comes to the same as using area indexes. Maybe only one mode is really necessary then in the end?

I thought the single tree mode could be useful if for example, single tree parameters such as trunk width from which we can get trunk area were known; but someone could still use this and just divide it by the area of the grid and this would give SAI (they would have to divide the leaf area and root area by the same term though). --- This makes me think I should maybe review the meaning of these area indexes and see how they are calculated because conducting area isn't the same as the cross-sectional area of a compartment (a cross sectional area is needed for the sigma in d theta/ dt = (1/(sigma*l))*(flux_in*AI_in - flux_out*AI_out)).
