### ISSUE TITLE
Add state boundary conditions

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLSM.jl#98]
**Is your feature request related to a problem? Please describe.**
Currently, boundary conditions in the land model are expressed in terms of fluxes (i.e. heat and/or water flux). We would like to be able to also specify state boundary conditions (i.e. temperature and/or water content). Any combination of different boundary conditions should be able to be used, in particular the case of one flux and one state.

**Describe the solution you'd like**
Create a new subtype of `AbstractBoundaryConditions` for state boundary conditions
Add new methods of `boundary_fluxes` to be able to handle any combination of 1 or 2 flux and/or state boundary conditions

**Describe alternatives you've considered**

**Additional context**
Linked PR: #103

**Comment by kmdeck** [comment]
@juliasloan25, could you open a PR for your branch and link it to this issue? Thanks!
